package io.neonjs.jit

import io.neonjs.compiler.*
import io.neonjs.runtime.*
import io.neonjs.vm.*

/** Entry point implemented by generated classes. */
interface CompiledCode {
    fun run(f: Frame): Any?
}

/**
 * Static helpers called from JVM bytecode generated by [JvmCompiler]. Each mirrors the semantics of the
 * corresponding interpreter instruction (see Interpreter.run). Parameters are typed loosely (Object) so the
 * generated code needs no casts.
 */
@Suppress("unused")
object JitRt {
    private fun tdzError(name: String) = JSException.referenceError(
        if (name == "this") "Must call super constructor in derived class before accessing 'this' or returning from derived constructor"
        else "Cannot access '$name' before initialization"
    )

    @JvmStatic fun tdz(v: Any?, k: Int, consts: Array<Any?>): Any? {
        if (v === Uninitialized) throw tdzError(consts[k] as String)
        return v
    }

    @JvmStatic fun truthy(v: Any?): Boolean = if (v is Boolean) v else Ops.toBoolean(v)
    @JvmStatic fun isNullish(v: Any?): Boolean = v === Undefined || v === Null
    @JvmStatic fun isUndefined(v: Any?): Boolean = v === Undefined
    @JvmStatic fun toIntIndex(v: Any?): Int = (v as Double).toInt()

    // ------------------------------------------------------------------ environments

    @JvmStatic fun pushScope(f: Frame, consts: Array<Any?>, k: Int) {
        f.env = DeclEnv(f.env, consts[k] as ScopeInfo)
    }
    @JvmStatic fun popScope(f: Frame) { f.env = f.env!!.parent }
    @JvmStatic fun copyScope(f: Frame) { f.env = (f.env as DeclEnv).copy() }
    @JvmStatic fun pushWith(o: Any?, f: Frame) { f.env = ObjectEnv(f.env, o as JSObject, true) }
    @JvmStatic fun setEnv(v: Any?, f: Frame) { f.env = v as Env? }

    @JvmStatic fun loadEnv(f: Frame, h: Int, s: Int): Any? {
        var e = f.env
        var n = h
        while (n-- > 0) e = e!!.parent
        return (e as DeclEnv).slots[s]
    }

    @JvmStatic fun storeEnv(v: Any?, f: Frame, h: Int, s: Int) {
        var e = f.env
        var n = h
        while (n-- > 0) e = e!!.parent
        (e as DeclEnv).slots[s] = v
    }

    @JvmStatic fun loadEnvTdz(f: Frame, h: Int, s: Int, k: Int, consts: Array<Any?>): Any? {
        val v = loadEnv(f, h, s)
        if (v === Uninitialized) throw tdzError(consts[k] as String)
        return v
    }

    @JvmStatic fun initThisReg(v: Any?, old: Any?, f: Frame): Any? {
        if (old !== Uninitialized) throw JSException.referenceError("Super constructor may only be called once")
        f.thisValue = v
        return v
    }

    @JvmStatic fun initThisEnv(v: Any?, f: Frame, h: Int, s: Int) {
        var e = f.env
        var n = h
        while (n-- > 0) e = e!!.parent
        val de = e as DeclEnv
        if (de.slots[s] !== Uninitialized) throw JSException.referenceError("Super constructor may only be called once")
        de.slots[s] = v
    }

    @JvmStatic fun initThisName(v: Any?, f: Frame) = Rt.initThisDynamic(f.env, v)

    // ------------------------------------------------------------------ names & globals

    private fun strict(f: Frame) = f.code.flags and CodeBlock.STRICT != 0

    @JvmStatic fun loadName(f: Frame, name: Any?): Any? = Names.load(f.env, name as String, strict(f), false)
    @JvmStatic fun loadNameTypeof(f: Frame, name: Any?): Any? = Names.load(f.env, name as String, strict(f), true)
    @JvmStatic fun loadNameCall(f: Frame, name: Any?): Array<Any?> {
        val (v, t) = Names.loadForCall(f.env, name as String, strict(f))
        return arrayOf(v, t)
    }
    @JvmStatic fun storeName(v: Any?, f: Frame, name: Any?) = Names.store(f.env, name as String, v, strict(f), f.realm.globalEnv)
    @JvmStatic fun storeNameVar(v: Any?, f: Frame, name: Any?) = Rt.storeAnnexBVar(f.env, name as String, v, f.realm)
    @JvmStatic fun deleteName(f: Frame, name: Any?): Any? = Names.delete(f.env, name as String)
    @JvmStatic fun initName(v: Any?, f: Frame, name: Any?) = Names.initialize(f.env, name as String, v)
    @JvmStatic fun loadGlobal(f: Frame, site: Any?): Any? = GlobalCache.load(f.realm, site as GlobalSite, false)
    @JvmStatic fun loadGlobalTypeof(f: Frame, site: Any?): Any? = GlobalCache.load(f.realm, site as GlobalSite, true)
    @JvmStatic fun storeGlobal(v: Any?, f: Frame, site: Any?) = GlobalCache.store(f.realm, site as GlobalSite, v, strict(f))
    @JvmStatic fun initGlobalLex(v: Any?, f: Frame, name: Any?) = Rt.initGlobalLexical(f.realm, name as String, v)
    @JvmStatic fun resolveName(f: Frame, name: Any?): Any? = Names.resolve(f.env, name as String) ?: NameRef(null, name, -1, strict(f))
    @JvmStatic fun getRef(ref: Any?, f: Frame): Any? {
        val r = ref as NameRef
        return Names.getValue(if (r.env == null) null else r, r.name, strict(f), false)
    }
    @JvmStatic fun putRef(ref: Any?, v: Any?, f: Frame): Any? {
        val r = ref as NameRef
        Names.putValue(if (r.env == null) null else r, r.name, v, strict(f), f.realm.globalEnv)
        return v
    }

    // ------------------------------------------------------------------ function context

    @JvmStatic fun loadFunction(f: Frame): Any? = f.fn ?: Undefined
    @JvmStatic fun loadHome(f: Frame): Any? = f.fn?.homeObject ?: f.homeObject ?: Undefined
    @JvmStatic fun arg(f: Frame, i: Int): Any? {
        val a = f.args
        return if (i < a.size) a[i] else Undefined
    }
    @JvmStatic fun createArguments(f: Frame, mapped: Int): Any? =
        if (mapped == 1) Rt.createMappedArguments(f.fn!!, f.args, f.env as? DeclEnv, f.code.mappedSlots!!)
        else Rt.createUnmappedArguments(f.realm, f.args)
    @JvmStatic fun createRest(f: Frame, start: Int): Any? {
        val arr = JSArray(f.realm.arrayPrototype)
        val a = f.args
        for (i in start until a.size) arr.pushInit(a[i])
        return arr
    }

    // ------------------------------------------------------------------ errors

    @JvmStatic fun throwValue(v: Any?): Throwable = JSException(v)

    @JvmStatic fun throwError(kind: Int, k: Int, consts: Array<Any?>): Throwable {
        val msg = consts[k] as String
        return when (kind) {
            1 -> JSException.referenceError(msg)
            2 -> JSException.syntaxError(msg)
            3 -> JSException.rangeError(msg)
            else -> JSException.typeError(msg)
        }
    }

    @JvmStatic fun catchValue(t: Throwable, f: Frame): Any? = Rt.catchValue(t, f.realm, f, f.pc)

    // ------------------------------------------------------------------ properties

    @JvmStatic fun getProp(o: Any?, site: Any?, f: Frame): Any? {
        val s = site as PropSite
        return if (o is JSObject) PropCache.get(o, s) else Rt.getPrimitiveProp(f.realm, o, s.key)
    }

    @JvmStatic fun putProp(o: Any?, v: Any?, site: Any?, f: Frame): Any? {
        val s = site as PropSite
        if (o is JSObject) {
            if (!PropCache.put(o, s, v) && strict(f)) throw Rt.readOnlyError(s.key, o)
        } else Rt.putPrimitive(f.realm, o, s.key, v, strict(f))
        return v
    }

    @JvmStatic fun getElem(o: Any?, key: Any?, f: Frame): Any? = Rt.getElem(f.realm, o, key)

    @JvmStatic fun disposeNew(): Any? = Disposal.newCapability()
    @JvmStatic fun addDisposable(v: Any?, cap: Any?, hint: Int, f: Frame) = Disposal.add(f.realm, cap, v, hint)
    @JvmStatic fun disposeSync(cap: Any?, kind: Any?, value: Any?, f: Frame) = Disposal.disposeSync(f.realm, cap, kind, value)

    @JvmStatic fun newObjectLiteral(values: Array<Any?>, site: Any?, f: Frame): Any? =
        (site as ObjectLiteralSite).create(f.realm.objectPrototype, values)

    @JvmStatic fun putElem(o: Any?, key: Any?, v: Any?, f: Frame): Any? {
        Rt.putElem(f.realm, o, key, v, strict(f))
        return v
    }

    @JvmStatic fun deleteProp(o: Any?, key: Any?, f: Frame): Any? = Rt.deleteProp(f.realm, o, key!!, strict(f))
    @JvmStatic fun deleteElem(o: Any?, key: Any?, f: Frame): Any? = Rt.deleteProp(f.realm, o, Ops.toPropertyKey(Rt.keyForBase(o, key)), strict(f))
    @JvmStatic fun toPropertyKey(v: Any?): Any? = Ops.toPropertyKey(v)
    @JvmStatic fun keyForBase(o: Any?, k: Any?): Any? = Rt.keyForBase(o, k)
    @JvmStatic fun getSuper(thisV: Any?, key: Any?, base: Any?, f: Frame): Any? = Rt.getSuper(f.realm, thisV, Ops.toPropertyKey(key), base)
    @JvmStatic fun putSuper(thisV: Any?, key: Any?, base: Any?, v: Any?, f: Frame): Any? {
        Rt.putSuper(f.realm, thisV, Ops.toPropertyKey(key), base, v, strict(f))
        return v
    }
    @JvmStatic fun superBase(home: Any?): Any? = Rt.superBase(home)
    @JvmStatic fun getPrivate(o: Any?, pn: Any?): Any? = Rt.privateGet(o, pn as PrivateName)
    @JvmStatic fun putPrivate(o: Any?, pn: Any?, v: Any?): Any? {
        Rt.privateSet(o, pn as PrivateName, v)
        return v
    }
    @JvmStatic fun hasPrivate(pn: Any?, o: Any?): Any? = Rt.privateIn(pn as PrivateName, o)

    // ------------------------------------------------------------------ operators

    @JvmStatic fun add(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a + b else Ops.add(a, b)
    @JvmStatic fun sub(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a - b else Ops.sub(a, b)
    @JvmStatic fun mul(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a * b else Ops.mul(a, b)
    @JvmStatic fun div(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a / b else Ops.div(a, b)
    @JvmStatic fun mod(a: Any?, b: Any?): Any? = Ops.mod(a, b)
    @JvmStatic fun exp(a: Any?, b: Any?): Any? = Ops.exp(a, b)
    @JvmStatic fun shl(a: Any?, b: Any?): Any? = Ops.shl(a, b)
    @JvmStatic fun sar(a: Any?, b: Any?): Any? = Ops.sar(a, b)
    @JvmStatic fun shr(a: Any?, b: Any?): Any? = Ops.shr(a, b)
    @JvmStatic fun band(a: Any?, b: Any?): Any? = Ops.bitAnd(a, b)
    @JvmStatic fun bor(a: Any?, b: Any?): Any? = Ops.bitOr(a, b)
    @JvmStatic fun bxor(a: Any?, b: Any?): Any? = Ops.bitXor(a, b)
    @JvmStatic fun eq(a: Any?, b: Any?): Any? = Ops.looseEquals(a, b)
    @JvmStatic fun ne(a: Any?, b: Any?): Any? = !Ops.looseEquals(a, b)
    @JvmStatic fun seq(a: Any?, b: Any?): Any? = Ops.strictEquals(a, b)
    @JvmStatic fun sne(a: Any?, b: Any?): Any? = !Ops.strictEquals(a, b)
    @JvmStatic fun lt(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a < b else Ops.lt(a, b)
    @JvmStatic fun gt(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a > b else Ops.gt(a, b)
    @JvmStatic fun le(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a <= b else Ops.le(a, b)
    @JvmStatic fun ge(a: Any?, b: Any?): Any? = if (a is Double && b is Double) a >= b else Ops.ge(a, b)
    @JvmStatic fun instanceOf(a: Any?, b: Any?): Any? = Ops.instanceOf(a, b)
    @JvmStatic fun inOp(a: Any?, b: Any?): Any? = Ops.hasPropertyOp(a, b)
    @JvmStatic fun neg(a: Any?): Any? = Ops.neg(a)
    @JvmStatic fun toNumber(a: Any?): Any? = if (a is Double) a else Ops.toNumber(a)
    @JvmStatic fun not(a: Any?): Any? = !Ops.toBoolean(a)
    @JvmStatic fun bnot(a: Any?): Any? = Ops.bitNot(a)
    @JvmStatic fun typeOf(a: Any?): Any? = Ops.typeOf(a)
    @JvmStatic fun toNumeric(a: Any?): Any? = if (a is Double) a else Ops.toNumeric(a)
    @JvmStatic fun inc(a: Any?): Any? = if (a is Double) a + 1.0 else Ops.inc(a)
    @JvmStatic fun dec(a: Any?): Any? = if (a is Double) a - 1.0 else Ops.dec(a)
    @JvmStatic fun toStr(a: Any?): Any? = if (a is CharSequence) a else Ops.toString(a)
    @JvmStatic fun concat(a: Any?, b: Any?): Any? = Rope.concat(a as CharSequence, b as CharSequence)
    @JvmStatic fun toObject(a: Any?, f: Frame): Any? = Ops.toObject(f.realm, a)
    @JvmStatic fun requireCoercible(v: Any?): Any? {
        if (v === Undefined || v === Null) throw JSException.typeError("Cannot destructure '${Ops.toDisplayString(v)}' as it is ${Ops.toDisplayString(v)}.")
        return v
    }
    @JvmStatic fun checkObject(v: Any?, k: Int, consts: Array<Any?>): Any? {
        if (v !is JSObject) throw JSException.typeError(consts[k] as String)
        return v
    }
    @JvmStatic fun derivedReturn(v: Any?, thisV: Any?): Any? = DerivedResult(v, thisV)

    // ------------------------------------------------------------------ calls

    @JvmStatic fun call(fnv: Any?, thisV: Any?, args: Array<Any?>, f: Frame, pc: Int): Any? {
        f.pc = pc
        // JS functions directly, without the (megamorphic) virtual JSObject.call
        if (fnv is JSClosure) return Interpreter.callClosure(fnv, thisV, args)
        if (fnv is JSObject && fnv.special and JSObject.CALLABLE != 0) return fnv.call(thisV, args)
        throw Rt.notCallable(fnv, f.code, pc)
    }
    @JvmStatic fun call0(fnv: Any?, t: Any?, f: Frame, pc: Int): Any? = call(fnv, t, EMPTY_ARGS, f, pc)
    @JvmStatic fun call1(fnv: Any?, t: Any?, a: Any?, f: Frame, pc: Int): Any? = call(fnv, t, arrayOf(a), f, pc)
    @JvmStatic fun call2(fnv: Any?, t: Any?, a: Any?, b: Any?, f: Frame, pc: Int): Any? = call(fnv, t, arrayOf(a, b), f, pc)
    @JvmStatic fun call3(fnv: Any?, t: Any?, a: Any?, b: Any?, c: Any?, f: Frame, pc: Int): Any? = call(fnv, t, arrayOf(a, b, c), f, pc)
    @JvmStatic fun call4(fnv: Any?, t: Any?, a: Any?, b: Any?, c: Any?, d: Any?, f: Frame, pc: Int): Any? = call(fnv, t, arrayOf(a, b, c, d), f, pc)
    @JvmStatic fun callSpread(fnv: Any?, thisV: Any?, arr: Any?, f: Frame, pc: Int): Any? = call(fnv, thisV, Rt.arrayToArgs(arr as JSArray), f, pc)

    @JvmStatic fun construct(fnv: Any?, args: Array<Any?>, f: Frame, pc: Int): Any? {
        f.pc = pc
        if (fnv !is JSObject || fnv.special and JSObject.CONSTRUCTOR == 0) throw JSException.typeError("${Rt.calleeText(f.code, pc, fnv)} is not a constructor")
        return fnv.construct(args, fnv)
    }
    @JvmStatic fun newSpread(fnv: Any?, arr: Any?, f: Frame, pc: Int): Any? = construct(fnv, Rt.arrayToArgs(arr as JSArray), f, pc)

    @JvmStatic fun callEval(fnv: Any?, thisV: Any?, args: Array<Any?>, f: Frame, flags: Int, pc: Int): Any? {
        f.pc = pc
        return if (fnv === f.realm.evalFunction) Rt.directEval(f, args, flags and 1 != 0)
        else if (flags and 2 != 0) Interpreter.tailCall(f, fnv, thisV, args)
        else if (fnv is JSObject && fnv.isCallable) fnv.call(thisV, args)
        else throw Rt.notCallable(fnv, f.code, pc)
    }

    /** TAIL_CALL: returns [Interpreter.TAIL] (the compiled frame must return it) or the callee's result. */
    @JvmStatic fun tailCall(fnv: Any?, thisV: Any?, args: Array<Any?>, f: Frame, pc: Int): Any? {
        f.pc = pc
        return Interpreter.tailCall(f, fnv, thisV, args)
    }
    @JvmStatic fun callEvalSpread(fnv: Any?, thisV: Any?, arr: Any?, f: Frame, flags: Int, pc: Int): Any? =
        callEval(fnv, thisV, Rt.arrayToArgs(arr as JSArray), f, flags, pc)

    @JvmStatic fun superCall(func: Any?, nt: Any?, args: Array<Any?>, f: Frame, pc: Int): Any? {
        f.pc = pc
        return Rt.superCall(func, args, nt)
    }
    @JvmStatic fun superCallSpread(func: Any?, nt: Any?, arr: Any?, f: Frame, pc: Int): Any? = superCall(func, nt, Rt.arrayToArgs(arr as JSArray), f, pc)
    @JvmStatic fun getProtoOf(v: Any?): Any? = (v as JSObject).getPrototypeOf() ?: Null
    @JvmStatic fun initInstance(o: Any?, fn: Any?): Any? {
        Rt.initializeInstanceElements(o as JSObject, fn as JSClosure)
        return o
    }

    // ------------------------------------------------------------------ objects

    @JvmStatic fun newObject(f: Frame): Any? = JSObject(f.realm.objectPrototype)
    @JvmStatic fun newArray(f: Frame): Any? = JSArray(f.realm.arrayPrototype)
    @JvmStatic fun arrayPush(a: Any?, v: Any?): Any? { (a as JSArray).pushInit(v); return a }
    @JvmStatic fun arrayHole(a: Any?): Any? { (a as JSArray).pushHoleInit(); return a }
    @JvmStatic fun arraySpread(a: Any?, v: Any?, f: Frame): Any? { Rt.arraySpread(f.realm, a as JSArray, v); return a }
    @JvmStatic fun defineField(o: Any?, v: Any?, key: Any?): Any? { (o as JSObject).createDataPropertyOrThrow(key!!, v); return o }
    @JvmStatic fun defineFieldElem(o: Any?, key: Any?, v: Any?): Any? { (o as JSObject).createDataPropertyOrThrow(key!!, v); return o }
    @JvmStatic fun defineMethod(o: Any?, key: Any?, fn: Any?, op: Int, enumerable: Int): Any? {
        Rt.defineMethod(o as JSObject, key!!, fn as JSFunction, op, enumerable == 1)
        return o
    }
    @JvmStatic fun copyDataProps(t: Any?, s: Any?): Any? { Rt.copyDataProperties(t as JSObject, s, null); return t }
    @JvmStatic fun copyDataPropsExcl(t: Any?, s: Any?, keys: Array<Any?>): Any? {
        val excl = HashSet<Any>()
        for (k in keys) excl.add(k!!)
        Rt.copyDataProperties(t as JSObject, s, excl)
        return t
    }
    @JvmStatic fun setProto(o: Any?, v: Any?): Any? {
        if (v is JSObject || v === Null) (o as JSObject).setPrototypeOf(v as? JSObject)
        return o
    }
    @JvmStatic fun setFunctionName(key: Any?, fn: Any?, pk: Int, consts: Array<Any?>) =
        Rt.setFunctionName(fn as JSObject, key!!, if (pk >= 0) consts[pk] as String else null)
    @JvmStatic fun makeClosure(f: Frame, consts: Array<Any?>, k: Int): Any? = Rt.makeClosureIn(f, consts[k] as CodeBlock)
    @JvmStatic fun makeMethod(home: Any?, f: Frame, consts: Array<Any?>, k: Int): Any? = Rt.makeClosure(f.realm, consts[k] as CodeBlock, f.env, home as JSObject)
    @JvmStatic fun makeClass(heritage: Any?, name: Any?, f: Frame, consts: Array<Any?>, k: Int): Array<Any?> =
        Rt.makeClass(f.realm, consts[k] as CodeBlock, f.env, heritage, name)
    @JvmStatic fun newPrivateName(name: Any?): Any? = PrivateName(name as String)
    @JvmStatic fun addField(ctor: Any?, key: Any?, init: Any?) {
        val c = ctor as JSClosure
        var fl = c.fields
        if (fl == null) {
            fl = ArrayList()
            c.fields = fl
        }
        fl.add(FieldRecord(key!!, init))
    }
    @JvmStatic fun addPrivateMethod(ctor: Any?, pn: Any?, fn: Any?, kind: Int) = Rt.addPrivateMethod(ctor as JSClosure, pn as PrivateName, fn, kind)
    @JvmStatic fun staticPrivateMethod(ctor: Any?, pn: Any?, fn: Any?, kind: Int) = Rt.staticPrivateMethod(ctor as JSObject, pn as PrivateName, fn, kind)
    @JvmStatic fun runField(obj: Any?, key: Any?, fn: Any?, f: Frame, pc: Int) {
        f.pc = pc
        Rt.defineField(obj as JSObject, FieldRecord(key!!, fn))
    }

    // ------------------------------------------------------------------ iteration

    @JvmStatic fun getIterator(v: Any?, f: Frame): Any? = Iteration.getIterator(f.realm, v, false)
    /** Returns the next value, or NotFound when done. */
    @JvmStatic fun iterStep(rec: Any?): Any? = Iteration.stepValue(rec as IteratorRecord)
    @JvmStatic fun isNotFound(v: Any?): Boolean = v === NotFound
    @JvmStatic fun iterStepU(rec: Any?): Any? {
        val r = rec as IteratorRecord
        if (r.done) return Undefined
        val v = Iteration.stepValue(r)
        return if (v === NotFound) Undefined else v
    }
    @JvmStatic fun iterRest(rec: Any?, f: Frame): Any? = Iteration.rest(f.realm, rec as IteratorRecord)
    @JvmStatic fun iterClose(rec: Any?) = Iteration.closeNormal(rec as IteratorRecord)
    @JvmStatic fun iterCloseThrow(rec: Any?) = Iteration.closeOnThrow(rec as IteratorRecord)
    @JvmStatic fun forInStart(v: Any?, f: Frame): Any? = ForInIterator(Ops.toObject(f.realm, v))
    /** Next for-in key or null when done. */
    @JvmStatic fun forInNext(it: Any?): Any? = (it as ForInIterator).next()

    // ------------------------------------------------------------------ misc

    @JvmStatic fun debugger(f: Frame) = f.realm.agent.onDebugger(f)
    @JvmStatic fun templateObject(f: Frame, consts: Array<Any?>, k: Int): Any? = Rt.templateObject(f.realm, consts[k] as TemplateSite)
    @JvmStatic fun newRegExp(f: Frame, consts: Array<Any?>, k: Int): Any? = Rt.newRegExp(f.realm, consts[k] as RegExpSite)
    @JvmStatic fun importMeta(f: Frame): Any? = Rt.importMeta(f)
    @JvmStatic fun dynamicImport(spec: Any?, opts: Any?, f: Frame): Any? = Rt.dynamicImport(f, spec, opts)
    @JvmStatic fun classDefNew(c: Any?, p: Any?): Any? = Decorators.newClassDef(c, p)
    @JvmStatic fun classElement(def: Any?, decs: Any?, key: Any?, fn: Any?, flags: Int) = Decorators.addElement(def, decs, key, fn, flags)
    @JvmStatic fun classFinish(def: Any?) = Decorators.finish(def)
    @JvmStatic fun classDecorate(def: Any?, decs: Any?): Any? = Decorators.decorateClass(def, decs)
    @JvmStatic fun classStaticInit(def: Any?) = Decorators.staticInit(def)
    @JvmStatic fun dynamicImportPhase(spec: Any?, opts: Any?, f: Frame, phase: Any?): Any? = Modules.dynamicImport(f, spec, opts, phase as String)
    @JvmStatic fun declareGlobals(fns: Array<Any?>, f: Frame, consts: Array<Any?>, k: Int, pc: Int) {
        f.pc = pc
        Rt.declareGlobals(f.realm, consts[k] as DeclInfo, fns)
    }
    @JvmStatic fun declareEval(fns: Array<Any?>, f: Frame, consts: Array<Any?>, k: Int, pc: Int) {
        f.pc = pc
        Rt.declareEval(f, consts[k] as DeclInfo, fns)
    }
}
